# Generated by Django 4.2.30 on 2026-05-26 22:03

import apps.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('auth_header', apps.core.fields.EncryptedCharField(blank=True, help_text='Authorization header value — stored encrypted at rest')),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Used in the inbound URL: /webhooks/receive/<slug>/', unique=True)),
                ('secret', models.CharField(blank=True, help_text='HMAC secret — leave blank if signature_scheme is none', max_length=255)),
                ('signature_scheme', models.CharField(choices=[('github_hmac', 'GitHub HMAC-SHA256'), ('none', 'No Verification')], default='none', max_length=50)),
                ('rate_limit_per_minute', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('value', models.FloatField()),
                ('labels', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'timestamp'], name='core_metric_name_0881c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('raw_payload', models.JSONField()),
                ('headers', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('duplicate', 'Duplicate — Dropped'), ('sig_failed', 'Signature Verification Failed'), ('routed', 'Routed to Queue'), ('delivered', 'Delivered'), ('retrying', 'Retrying'), ('dead_lettered', 'Dead Lettered')], default='received', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='core.source')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'status', 'received_at'], name='core_webhoo_source__bfac4a_idx'), models.Index(fields=['idempotency_key'], name='core_webhoo_idempot_a117ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, db_index=True, help_text='Header-based filter, e.g. X-GitHub-Event value. Empty = match all.', max_length=100)),
                ('condition', models.JSONField(blank=True, default=dict, help_text='JSONPath conditions dict, e.g. {"ref": "refs/heads/main"}')),
                ('transformer_class', models.CharField(choices=[('github_to_slack', 'GitHub → Slack'), ('github_to_discord', 'GitHub → Discord'), ('calendar_to_db', 'Google Calendar → Database'), ('form_to_email', 'HTML Form → Email')], max_length=200)),
                ('priority', models.IntegerField(default=0, help_text='Lower number = evaluated first. Ties broken by pk.')),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.IntegerField(blank=True, help_text='Overrides source default if set', null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.destination')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.source')),
            ],
            options={
                'ordering': ['priority', 'pk'],
                'indexes': [models.Index(fields=['source', 'event_type', 'is_active', 'priority'], name='core_route_source__27603f_idx')],
            },
        ),
    ]
