# Generated by Django 4.2.30 on 2026-05-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='transformer_class',
            field=models.CharField(choices=[('github_to_slack', 'GitHub → Slack'), ('github_to_discord', 'GitHub → Discord'), ('calendar_to_db', 'Google Calendar → Database'), ('form_to_email', 'HTML Form → Email'), ('passthrough', 'Passthrough (no transform)')], max_length=200),
        ),
    ]
